spring:
#  config:
#    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  # security:
  #   user:
  #     name: user
  #     password: 1234
  data:
    mongodb:
      uri: mongodb+srv://whai:RAf!eWr-bAmf!L5@cluster0.cefghb6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: chat_app
logging.level:
  org.hibernate.SQL: debug
server:
  port: 8088
logging:
  level:
    org:
      springframework:
        security: DEBUG
jwt:
  secret: lVUiTGbxj4xgW5orFkfdNP72414P5q7ysgJi0rBSY9LwIWkjMY9VrxXV6BdF3bR+wpUgx/vQniz5lqNPbPwRPA==

  expiration: 86400000  # 1 day in milliseconds