spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  # security:
  #   user:
  #     name: user
  #     password: 1234
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${DATABASE_NAME}
logging.level:
  org.hibernate.SQL: debug
server:
  port: 8088
logging:
  level:
    org:
      springframework:
        security: DEBUG
