spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  # security:
  #   user:
  #     name: user
  #     password: 1234
logging.level:
  org.hibernate.SQL: debug